export const GET_DATA = "GET_DATA";
export const ADD_DATA = "ADD_DATA";
export const EDIT_DATA = "EDIT_DATA";
export const UPDATE_DATA = "UPDATE_DATA";
export const DELETE_DATA = "DELETE_DATA";
export const FIREBASE_DATA = "FIREBASE_DATA";
export const FIREBASE_UID = "FIREBASE_UID";
export const CANCEL_EDIT = "CANCEL_EDIT";
export const SET_LOADING="SET_LOADING"
